### PR TITLE
Add a test for extensions in different order

### PR DESCRIPTION
**Pull request by paulkernfeld**
Fix standard and improve organization of other tests

### CODE REVIEW

**Comment by piedshag** [comment]
@paulkernfeld  Also just wondering why we are doing it in hypercore not hyperdrive. Is hypercore eventually going to be merged into hyperdrive?

**Comment by paulkernfeld** [comment]
As I understand it, hyperdrive is going to be refactored so that it depends on hypercore. Hypercore is going to be for replicating binary streams of data, and hyperdrive is going to have all the stuff that has to do with files. Since we don't need files for dynamic feeds, I think they should be in hypercore. Of course, there's a lot of interesting stuff that we can do by combining dynamic feeds with hyperdrive!

**Comment by piedshag** [comment]
@paulkernfeld i have completely rewritten the api please check my pull request to hypercore

**Comment by piedshag** [comment]
@paulkernfeld i like your approach to the dynamic feed problem. It can probably be implemented using the extension protocol and substack's [bittorrent-dht-store-keypair](https://github.com/substack/bittorrent-dht-store-keypair) module. I might try to implement it after the pr gets merged.

**Comment by piedshag** [comment]
@paulkernfeld i have too much time on my hands. [signing values extension](https://github.com/piedshag/hypercore/blob/master/test/extensions.js#L95). Tell me what you think of it.

**Pull request closed without merging**
